services:
  postgres:
    image: postgres:16
    container_name: postgres-docscan
    environment:
      POSTGRES_USER: docscan
      POSTGRES_PASSWORD: docscan
      POSTGRES_DB: docscan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docscan-net

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - docscan-net

  api:
    build: .
    container_name: docscan-api
    ports:
      - "8000:8000"
    environment:
      S3_ENDPOINT: http://minio:9000
      POSTGRES_HOST: postgres
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    depends_on:
      - postgres
      - minio
    networks:
      - docscan-net



  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - docscan-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - docscan-net

networks:
  docscan-net:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  prometheus_data:
  grafana_data:
